#ifndef KEYBOARD_H
#define KEYBOARD_H

#include<stdint.h>
#include<stdbool.h>

#define CMD_SET_LEDS 0xED
#define CMD_ECHO 0xEE
#define CMD_GET_SET_SCANCODE_SET 0xF0
#define CMD_IDENTIFY 0xF2
#define CMD_TYPEMATIC_RATE_DELAY 0xF3
#define CMD_ENABLE_SCANNING 0xF4
#define CMD_DISABLE_SCANNING 0xF5
#define CMD_DEFAULT_PARAMS 0xF6
#define CMD_AUTOREPEAT 0xF7
#define CMD_MAKE_RELEASE 0xF8
#define CMD_MAKE_ONLY 0xF9
#define CMD_TYPEMATIC_AUTO_MAKE_RELEASE 0xFA
#define CMD_KEY_TO_TYPEMATIC_AUTOREPEAT 0xFB
#define CMD_KEY_TO_MAKE_RELEASE 0xFC
#define CMD_KEY_TO_MAKE_ONLY 0xFD
#define CMD_RESEND 0xFE
#define CMD_RESET_SELF_TEST 0xFF

#define DETECTION_ERROR 0x00
#define SELF_TEST_PASSED 0xAA
#define ECHO_RESPONCE 0xEE
#define ACK 0xFA
#define SELF_TEST_FAILED0 0xFC
#define SELF_TEST_FAILED1 0xFD
#define RESEND 0xFE
#define ERROR 0xFF

/* All other's sent are scancodes */

#endif

